version: 0.0.2.0.{build}
image: Visual Studio 2015

branches:
  only:
    - V_7_3w

build_script:
  - ps: |
      Import-Module $env:APPVEYOR_BUILD_FOLDER\contrib\win32\openssh\AppVeyor.psm1
      Invoke-AppVeyorBuild

before_test:
  - ps: Install-OpenSSH
  - ps: Write-Verbose "Restart computer ..."
  - ps: Restart-Computer -ComputerName localhost -Force
  - ps: Start-Sleep -s 5 # Needs to be proceeded with -ps: as it's interpreted by AppVeyor
  - ps: Write-Verbose "Restart computer completed"

test_script:
  - ps: |
      Import-Module $env:APPVEYOR_BUILD_FOLDER\contrib\win32\openssh\AppVeyor.psm1
  - ps: Run-OpenSSHTests -uploadResults
      
on_finish:
  - ps: Publish-Artifact